version: '3.8'

services:
  nest:
    image: stockupby/nest-service
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    volumes:
      - logs_volume:/var/logs/nest

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER= ${DB_USERNAME}
      - POSTGRES_PASSWORD= ${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      - logs_volume:/var/logs/postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgres_data:
  logs_volume:
