version: '3.1'

services:
  nest:
    build: .
    ports:
      - '4000:4000'

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_DATABASE=service
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
